Added - BE_FE- integration with error handling
havenwork/productivitytracker pull request #14
Opened 2024-03-07 10:17 UTC by Anshuman1803

Task 1: Implement frontend error handling for API calls. - Completed

Task 2: Connect authentication views to backend APIs. -Completed

2024-03-08 12:30 UTC, lakshay927 requested changes
changes

2024-03-08 12:30 UTC, lakshay927 commented on Backend/config.env
email ssl port is 465 thats not backend port revert it

2024-03-08 12:30 UTC, lakshay927 commented on src/App.css
try to get rid of this css file and use tailwind

2024-03-08 12:30 UTC, lakshay927 commented on src/helpers/formValidation.js
can we use it with a module for validation to make it easier

2024-03-08 19:41 UTC, Anshuman1803 commented on Backend/config.env
DONE

2024-03-08 19:41 UTC, Anshuman1803 commented on src/App.css
DONE

2024-03-09 07:07 UTC, Anshuman1803 commented on src/helpers/formValidation.js
I convert the long validation helper function into separate modules:

- isUserName : for validating the user name
- isFullName : for validating the full name
- isEmail : for validating the email address
- isPassword : for validating the password

2024-03-09 12:08 UTC, lakshay927 approved these changes
looks good

2024-03-09 12:10 UTC, merged